// <auto-generated />
using CareerPanda.DataAccess.Entities.Api;
using CareerPanda.DataAccess.Entities.Cp;
using CareerPanda.DataAccess.Entities.Md;
using Microsoft.EntityFrameworkCore;

namespace CareerPanda.DataAccess.PostgreSQL;

public partial class CareerPandaDbContext
{
    static partial void ConfigureEnums(ModelBuilder modelBuilder)
    {        // PostgreSQL enum column types
        modelBuilder.Entity<CpConsultantApplication>().Property(e => e.Status).HasColumnType("cp.consultant_application_status");
        modelBuilder.Entity<CpProfileRequest>().Property(e => e.Status).HasColumnType("cp.consultant_application_status");
        modelBuilder.Entity<CpUserSubscription>().Property(e => e.Status).HasColumnType("cp.user_subscriptions_status_enum");
    }
}
