// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Api;

[Table("recruitee_board_tokens", Schema = "api")]
public class ApiRecruiteeBoardToken
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("company_name")]
    public string CompanyName { get; set; }

    // The {subdomain} in https://{subdomain}.recruitee.com/api/offers/
    [Column("board_token")]
    public string BoardToken { get; set; }

    [Column("industry")]
    public string? Industry { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("http_code")]
    public short? HttpCode { get; set; }

    [Column("job_count")]
    public int? JobCount { get; set; }

    [Column("api_url")]
    public string ApiUrl { get; set; }

    [Column("board_url")]
    public string BoardUrl { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }
}
