// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Api;

[Table("workday_board_tokens", Schema = "api")]
public class ApiWorkdayBoardToken
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("company_name")]
    public string CompanyName { get; set; }

    [Column("company_slug")]
    public string CompanySlug { get; set; }

    [Column("wd_instance")]
    public string WdInstance { get; set; }

    [Column("site_id")]
    public string SiteId { get; set; }

    [Column("industry")]
    public string? Industry { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("http_code")]
    public short? HttpCode { get; set; }

    [Column("job_count")]
    public int? JobCount { get; set; }

    [Column("api_url")]
    public string ApiUrl { get; set; }

    [Column("board_url")]
    public string BoardUrl { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }
}
