// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("ats_runs", Schema = "cp")]
public partial class CpAtsRun
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("resume_id")]
    public long? ResumeId { get; set; }

    [Column("snapshot_version")]
    public int? SnapshotVersion { get; set; }

    [Column("score")]
    public int Score { get; set; }

    [Column("score_band")]
    public string? ScoreBand { get; set; }

    [Column("result_json")]
    public string ResultJson { get; set; }

    [Column("source")]
    public string Source { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

}
