// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("campaigns", Schema = "cp")]
public partial class CpCampaign
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("template_id")]
    public long? TemplateId { get; set; }

    [Column("user_count")]
    public long? UserCount { get; set; }

    [Column("status")]
    public long? Status { get; set; }

    [Column("created_by")]
    public long CreatedBy { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("campaign_type")]
    public string? CampaignType { get; set; }

    [Column("subject")]
    public string? Subject { get; set; }

    [Column("body_content")]
    public string? BodyContent { get; set; }

    [Column("target_audience")]
    public string? TargetAudience { get; set; }

    [Column("location_filter")]
    public string? LocationFilter { get; set; }

    [Column("scheduled_at")]
    public DateTime? ScheduledAt { get; set; }

    [Column("started_at")]
    public DateTime? StartedAt { get; set; }

    [Column("completed_at")]
    public DateTime? CompletedAt { get; set; }

    [Column("paused_at")]
    public DateTime? PausedAt { get; set; }

    [Column("cancelled_at")]
    public DateTime? CancelledAt { get; set; }

    [Column("cancelled_by")]
    public long? CancelledBy { get; set; }

    [Column("sent_count")]
    public int? SentCount { get; set; }

    [Column("delivered_count")]
    public int? DeliveredCount { get; set; }

    [Column("failed_count")]
    public int? FailedCount { get; set; }

    [Column("opened_count")]
    public int? OpenedCount { get; set; }

    [Column("clicked_count")]
    public int? ClickedCount { get; set; }

}
