// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("careerpage_jobs", Schema = "cp")]
public partial class CpCareerpageJob
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("department")]
    public string Department { get; set; }

    [Column("location")]
    public string Location { get; set; }

    [Column("employment_type")]
    public string EmploymentType { get; set; }

    [Column("requirements")]
    public string? Requirements { get; set; }

    [Column("responsibilities")]
    public string? Responsibilities { get; set; }

    [Column("salary_range")]
    public string? SalaryRange { get; set; }

    [Column("tags")]
    public string? Tags { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; }

    [Column("application_email")]
    public string? ApplicationEmail { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

}
