// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("company_reviews", Schema = "cp")]
public partial class CpCompanyReview
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("company_id")]
    public long CompanyId { get; set; }

    [Column("review_title")]
    public string? ReviewTitle { get; set; }

    [Column("employment_status")]
    public string EmploymentStatus { get; set; }

    [Column("tenure_months")]
    public int? TenureMonths { get; set; }

    [Column("experience_years")]
    public decimal? ExperienceYears { get; set; }

    [Column("overall_rating")]
    public decimal OverallRating { get; set; }

    [Column("rating_culture")]
    public decimal? RatingCulture { get; set; }

    [Column("rating_compensation_benefits")]
    public decimal? RatingCompensationBenefits { get; set; }

    [Column("rating_work_life_balance")]
    public decimal? RatingWorkLifeBalance { get; set; }

    [Column("rating_management")]
    public decimal? RatingManagement { get; set; }

    [Column("rating_career_growth")]
    public decimal? RatingCareerGrowth { get; set; }

    [Column("rating_job_security")]
    public decimal? RatingJobSecurity { get; set; }

    [Column("diversity_inclusion")]
    public decimal? DiversityInclusion { get; set; }

    [Column("pros")]
    public string? Pros { get; set; }

    [Column("cons")]
    public string? Cons { get; set; }

    [Column("advice_to_management")]
    public string? AdviceToManagement { get; set; }

    [Column("recommend_company")]
    public int? RecommendCompany { get; set; }

    [Column("is_anonymous")]
    public bool IsAnonymous { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("moderated_by")]
    public long? ModeratedBy { get; set; }

    [Column("moderated_on")]
    public DateTime? ModeratedOn { get; set; }

    [Column("moderation_notes")]
    public string? ModerationNotes { get; set; }

    [Column("helpful_count")]
    public int HelpfulCount { get; set; }

    [Column("not_helpful_count")]
    public int NotHelpfulCount { get; set; }

    [Column("comment_count")]
    public int CommentCount { get; set; }

    [Column("is_consent")]
    public bool? IsConsent { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("employment_type")]
    public int? EmploymentType { get; set; }

    [Column("work_location")]
    public string? WorkLocation { get; set; }

    [Column("image_urls")]
    public string? ImageUrls { get; set; }

    [Column("total_company_experience")]
    public decimal? TotalCompanyExperience { get; set; }

    [Column("working_period_start")]
    public DateTime? WorkingPeriodStart { get; set; }

    [Column("working_period_end")]
    public DateTime? WorkingPeriodEnd { get; set; }

    [Column("job_role_id")]
    public long? JobRoleId { get; set; }

}
