// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("consultation_feedback", Schema = "cp")]
public partial class CpConsultationFeedback
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_consultation_id")]
    public long? UserConsultationId { get; set; }

    [Column("user_id")]
    public long? UserId { get; set; }

    [Column("consultant_id")]
    public long? ConsultantId { get; set; }

    [Column("rating")]
    public decimal? Rating { get; set; }

    [Column("feedback")]
    public string? Feedback { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("response")]
    public string? Response { get; set; }

    [Column("responded_on")]
    public DateTime? RespondedOn { get; set; }

}
