// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("educations", Schema = "cp")]
public partial class CpEducation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("resume_id")]
    public long ResumeId { get; set; }

    [Column("start_date")]
    public DateOnly? StartDate { get; set; }

    [Column("end_date")]
    public DateOnly? EndDate { get; set; }

    [Column("description")]
    public string? Description { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("field_of_study_id")]
    public int? FieldOfStudyId { get; set; }

    [Column("degree")]
    public string? Degree { get; set; }

    [Column("gpa")]
    public decimal? Gpa { get; set; }

    [Column("location")]
    public string? Location { get; set; }

    [Column("school_name")]
    public string SchoolName { get; set; }

}
