// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("event_hosts", Schema = "cp")]
public partial class CpEventHost
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("event_id")]
    public long EventId { get; set; }

    [Column("host_name")]
    public string HostName { get; set; }

    [Column("host_image")]
    public string? HostImage { get; set; }

    [Column("is_primary")]
    public bool? IsPrimary { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

}
