// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("events", Schema = "cp")]
public partial class CpEvent
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("event_name")]
    public string EventName { get; set; }

    [Column("cover_image")]
    public string? CoverImage { get; set; }

    [Column("event_description")]
    public string? EventDescription { get; set; }

    [Column("start_date")]
    public DateOnly StartDate { get; set; }

    [Column("start_time")]
    public string StartTime { get; set; }

    [Column("payment_amount")]
    public decimal? PaymentAmount { get; set; }

    [Column("is_free")]
    public bool? IsFree { get; set; }

    [Column("status")]
    public string? Status { get; set; }

    [Column("registration_end_date")]
    public DateOnly? RegistrationEndDate { get; set; }

    [Column("meeting_link")]
    public string? MeetingLink { get; set; }

    [Column("capacity")]
    public int? Capacity { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("media_urls")]
    public string[]? MediaUrls { get; set; }

    [Column("media_assets")]
    public string[]? MediaAssets { get; set; }

    [Column("timezone")]
    public string? Timezone { get; set; }

    [Column("total_registered")]
    public int? TotalRegistered { get; set; }

    [Column("category_ids")]
    public string[]? CategoryIds { get; set; }

    [Column("duration_min")]
    public int? DurationMin { get; set; }

}
