// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("likes", Schema = "cp")]
public partial class CpLike
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("post_id")]
    public long PostId { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

}
