// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("notification_preference", Schema = "cp")]
public partial class CpNotificationPreference
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("role_id")]
    public int RoleId { get; set; }

    [Column("email_notifications")]
    public bool EmailNotifications { get; set; }

    [Column("weekly_reports")]
    public bool WeeklyReports { get; set; }

    [Column("consultation_alerts")]
    public bool ConsultationAlerts { get; set; }

    [Column("marketing_emails")]
    public bool MarketingEmails { get; set; }

    [Column("channels_json")]
    public string ChannelsJson { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }

}
