// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("referrals_requests", Schema = "cp")]
public partial class CpReferralsRequest
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public long? UserId { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("email")]
    public string? Email { get; set; }

    [Column("mobile_no")]
    public string? MobileNo { get; set; }

    [Column("city")]
    public string? City { get; set; }

    [Column("state")]
    public string? State { get; set; }

    [Column("country")]
    public string? Country { get; set; }

    [Column("appling_position")]
    public string? ApplingPosition { get; set; }

    [Column("target_companies")]
    public string? TargetCompanies { get; set; }

    [Column("job_link")]
    public string? JobLink { get; set; }

    [Column("linkedin_url")]
    public string? LinkedinUrl { get; set; }

    [Column("git_hub_url")]
    public string? GitHubUrl { get; set; }

    [Column("resume")]
    public string? Resume { get; set; }

    [Column("skills")]
    public string[]? Skills { get; set; }

    [Column("extra_details")]
    public string? ExtraDetails { get; set; }

    [Column("currently_working")]
    public bool? CurrentlyWorking { get; set; }

    [Column("current_company")]
    public string? CurrentCompany { get; set; }

    [Column("current_role_name")]
    public string? CurrentRoleName { get; set; }

    [Column("current_salary")]
    public decimal? CurrentSalary { get; set; }

    [Column("y_refer")]
    public string? YRefer { get; set; }

    [Column("terms_aggree")]
    public bool? TermsAggree { get; set; }

    [Column("previously_applied")]
    public bool? PreviouslyApplied { get; set; }

    [Column("notice_period")]
    public int? NoticePeriod { get; set; }

    [Column("is_placed")]
    public bool? IsPlaced { get; set; }

    [Column("placed_company")]
    public string? PlacedCompany { get; set; }

    [Column("placed_salary")]
    public decimal? PlacedSalary { get; set; }

    [Column("refered_by")]
    public string? ReferedBy { get; set; }

    [Column("handled_by")]
    public string? HandledBy { get; set; }

    [Column("expected_salary")]
    public decimal? ExpectedSalary { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("commission_percentage")]
    public decimal? CommissionPercentage { get; set; }

    [Column("commission_amount")]
    public decimal? CommissionAmount { get; set; }

    [Column("rejection_reason")]
    public string? RejectionReason { get; set; }

    [Column("referral_attempt_number")]
    public int? ReferralAttemptNumber { get; set; }

}
