// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("user_consultations", Schema = "cp")]
public partial class CpUserConsultation
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("user_id")]
    public long? UserId { get; set; }

    [Column("consultant_id")]
    public long? ConsultantId { get; set; }

    [Column("service_id")]
    public long ServiceId { get; set; }

    [Column("transaction_id")]
    public long? TransactionId { get; set; }

    [Column("invoice_url")]
    public string? InvoiceUrl { get; set; }

    [Column("scheduled_at")]
    public DateTime ScheduledAt { get; set; }

    [Column("duration_min")]
    public int DurationMin { get; set; }

    [Column("paid_amount")]
    public decimal PaidAmount { get; set; }

    [Column("time_zone")]
    public string? TimeZone { get; set; }

    [Column("currency")]
    public string? Currency { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("meeting_link")]
    public string? MeetingLink { get; set; }

    [Column("notes_from_user")]
    public string? NotesFromUser { get; set; }

    [Column("notes_for_consultant")]
    public string? NotesForConsultant { get; set; }

    [Column("requested_on")]
    public DateTime RequestedOn { get; set; }

    [Column("accepted_on")]
    public DateTime? AcceptedOn { get; set; }

    [Column("rejected_on")]
    public DateTime? RejectedOn { get; set; }

    [Column("cancelled_on")]
    public DateTime? CancelledOn { get; set; }

    [Column("rescheduled_on")]
    public DateTime? RescheduledOn { get; set; }

    [Column("completed_on")]
    public DateTime? CompletedOn { get; set; }

    [Column("cancelled_by")]
    public long? CancelledBy { get; set; }

    [Column("cancelled_reason")]
    public string? CancelledReason { get; set; }

    [Column("rescheduled_reason")]
    public string? RescheduledReason { get; set; }

    [Column("rescheduled_id")]
    public long? RescheduledId { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("event_id")]
    public string? EventId { get; set; }

    [Column("resume_url")]
    public string? ResumeUrl { get; set; }

    [Column("consultant_message")]
    public string? ConsultantMessage { get; set; }

    [Column("user_admin_request")]
    public string? UserAdminRequest { get; set; }

    [Column("locked_commission_source")]
    public string? LockedCommissionSource { get; set; }

    [Column("locked_commission_percentage")]
    public decimal? LockedCommissionPercentage { get; set; }

    [Column("locked_admin_commission_amount")]
    public decimal? LockedAdminCommissionAmount { get; set; }

    [Column("locked_consultant_payout_amount")]
    public decimal? LockedConsultantPayoutAmount { get; set; }

    [Column("commission_locked_on")]
    public DateTime? CommissionLockedOn { get; set; }

    [Column("commission_lock_version")]
    public int? CommissionLockVersion { get; set; }

    [Column("is_free_consultation")]
    public bool? IsFreeConsultation { get; set; }

    [Column("discount_applied")]
    public decimal? DiscountApplied { get; set; }

    [Column("category_id")]
    public int? CategoryId { get; set; }

}
