// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Cp;

[Table("user_subscriptions", Schema = "cp")]
public partial class CpUserSubscription
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("subscription_id")]
    public int SubscriptionId { get; set; }

    [Column("start_date")]
    public DateTime StartDate { get; set; }

    [Column("end_date")]
    public DateTime EndDate { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("user_id")]
    public int? UserId { get; set; }

    [Column("invoice_url")]
    public string? InvoiceUrl { get; set; }

    [Column("referrer_id")]
    public string? ReferrerId { get; set; }

    [Column("referral_amount")]
    public decimal? ReferralAmount { get; set; }

    [Column("paid_amount")]
    public decimal? PaidAmount { get; set; }

    [Column("transaction_id")]
    public string? TransactionId { get; set; }

    [Column("trial_active")]
    public bool TrialActive { get; set; }

    [Column("trial_end_date")]
    public DateTime? TrialEndDate { get; set; }

    [Column("is_upgraded")]
    public bool? IsUpgraded { get; set; }

    [Column("upgraded_type")]
    public string? UpgradedType { get; set; }

    [Column("max_resumes_download")]
    public int? MaxResumesDownload { get; set; }

    [Column("max_cover_letters_download")]
    public int? MaxCoverLettersDownload { get; set; }

    [Column("max_jobs_apply")]
    public int? MaxJobsApply { get; set; }

    [Column("max_jobs_tailor")]
    public int? MaxJobsTailor { get; set; }

    [Column("max_ats_checks")]
    public int? MaxAtsChecks { get; set; }

    [Column("max_job_match")]
    public int? MaxJobMatch { get; set; }

    [Column("max_resumes_build")]
    public int? MaxResumesBuild { get; set; }

    [Column("remaining_resumes_download")]
    public int? RemainingResumesDownload { get; set; }

    [Column("remaining_cover_letters_download")]
    public int? RemainingCoverLettersDownload { get; set; }

    [Column("remaining_jobs_apply")]
    public int? RemainingJobsApply { get; set; }

    [Column("remaining_jobs_tailor")]
    public int? RemainingJobsTailor { get; set; }

    [Column("remaining_ats_checks")]
    public int? RemainingAtsChecks { get; set; }

    [Column("remaining_job_match")]
    public int? RemainingJobMatch { get; set; }

    [Column("remaining_resumes_build")]
    public int? RemainingResumesBuild { get; set; }

    [Column("is_addon")]
    public bool? IsAddon { get; set; }

    [Column("max_free_consult")]
    public int? MaxFreeConsult { get; set; }

    [Column("max_discount_consult")]
    public int? MaxDiscountConsult { get; set; }

    [Column("consult_service_ids")]
    public string? ConsultServiceIds { get; set; }

    [Column("consult_category_ids")]
    public string[]? ConsultCategoryIds { get; set; }

    [Column("remain_free_consult")]
    public int? RemainFreeConsult { get; set; }

    [Column("remain_discount_consult")]
    public int? RemainDiscountConsult { get; set; }

    [Column("remain_service_ids")]
    public string? RemainServiceIds { get; set; }

    [Column("remain_category_ids")]
    public string[]? RemainCategoryIds { get; set; }

}
