// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Md;

[Table("cover_letter_templates", Schema = "md")]
public partial class MdCoverLetterTemplate
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("template_name")]
    public string TemplateName { get; set; }

    [Column("description")]
    public string? Description { get; set; }

    [Column("html_code")]
    public string HtmlCode { get; set; }

    [Column("template_type")]
    public string? TemplateType { get; set; }

    [Column("custom_tag")]
    public string? CustomTag { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

    [Column("updated_on")]
    public DateTime? UpdatedOn { get; set; }

    [Column("placeholders")]
    public string? Placeholders { get; set; }

    [Column("preview_image_url")]
    public string? PreviewImageUrl { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; }

}
