// <auto-generated />
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareerPanda.DataAccess.Entities.Md;

[Table("field_of_study", Schema = "md")]
public partial class MdFieldOfStudy
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("degree_id")]
    public int? DegreeId { get; set; }

    [Column("slug")]
    public string Slug { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("description")]
    public string? Description { get; set; }

    [Column("created_on")]
    public DateTime CreatedOn { get; set; }

}
