-- BambooHR Board Tokens — company slugs
-- API pattern : GET https://{slug}.bamboohr.com/careers/list
-- Board URL   : https://{slug}.bamboohr.com/careers
--
-- Usage: Run once in Railway PostgreSQL console.
-- Status starts as 'UNKNOWN' — the handler will mark invalid ones after first run.

CREATE TABLE IF NOT EXISTS api.bamboohr_board_tokens (
    id           SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    board_token  VARCHAR(255) NOT NULL UNIQUE,
    industry     VARCHAR(255),
    status       VARCHAR(50)  NOT NULL DEFAULT 'UNKNOWN',
    http_code    SMALLINT,
    job_count    INTEGER,
    api_url      VARCHAR(500),
    board_url    VARCHAR(500),
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO api.bamboohr_board_tokens (company_name, board_token, api_url, board_url, status, created_at, updated_at)
SELECT
    INITCAP(REPLACE(slug, '-', ' '))                   AS company_name,
    slug                                               AS board_token,
    'https://' || slug || '.bamboohr.com/careers/list' AS api_url,
    'https://' || slug || '.bamboohr.com/careers'      AS board_url,
    'UNKNOWN'                                          AS status,
    NOW(), NOW()
FROM (VALUES
    ('100percentgroup'),
    ('1010games'),
    ('10squared'),
    ('10strawberrystreet'),
    ('10tengaming'),
    ('10web'),
    ('116andwest'),
    ('120water'),
    ('12thtribe'),
    ('1648factory'),
    ('17capital'),
    ('17live'),
    ('17triggers'),
    ('1office'),
    ('1stmile'),
    ('1valet'),
    ('2020mobile'),
    ('2025canadagames'),
    ('2050partners'),
    ('206toursold'),
    ('211la'),
    ('21stcenturyrehab'),
    ('22w2'),
    ('24hourcrafts'),
    ('24i'),
    ('24metrics'),
    ('24slg'),
    ('28b'),
    ('28stone'),
    ('2c2b'),
    ('2circleinc'),
    ('2innovateit'),
    ('2ndfamilyinc'),
    ('30fe'),
    ('315logistics'),
    ('31greenltd'),
    ('321theagency'),
    ('333rent'),
    ('350'),
    ('35n'),
    ('360vuz'),
    ('360wowinc'),
    ('365bookspro'),
    ('383project'),
    ('3and2baseball'),
    ('3ap'),
    ('3cat'),
    ('3fs'),
    ('3iq'),
    ('3mtt'),
    ('3p'),
    ('3peaksadvisors'),
    ('3rddegreescreening'),
    ('3riverscommunitycare'),
    ('3tgstaffingsolutions'),
    ('3yourmind'),
    ('401auto'),
    ('415'),
    ('42crunch'),
    ('4dmedical'),
    ('4medica'),
    ('4moms'),
    ('4seasonstransport'),
    ('4thdimension'),
    ('4thsecond'),
    ('50can'),
    ('50north'),
    ('5icloudsolutions'),
    ('5starcares'),
    ('603legalaid'),
    ('6kinc'),
    ('826boston'),
    ('8rivers'),
    ('954consultants'),
    ('97thfloor'),
    ('98ventures'),
    ('99drive'),
    ('9h'),
    ('9spokes')
) AS t(slug)
ON CONFLICT (board_token) DO NOTHING;
