using System.Text;
using Npgsql;

namespace SchemaInspector;

public static class EntityGenerator
{
    private static readonly HashSet<string> SkipTables = new(StringComparer.OrdinalIgnoreCase);

    public static async Task GenerateAsync(string connectionString, string outputRoot, string dbContextDir)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync();

        var tables = await LoadTablesAsync(conn);
        var columnsByTable = await LoadColumnsAsync(conn);
        var pkByTable = await LoadPrimaryKeysAsync(conn);
        var enumColumns = new List<(string Schema, string Table, string Column, string UdtName)>();

        Directory.CreateDirectory(Path.Combine(outputRoot, "Api"));
        Directory.CreateDirectory(Path.Combine(outputRoot, "Cp"));
        Directory.CreateDirectory(Path.Combine(outputRoot, "Md"));

        var dbSetLines = new StringBuilder();
        var enumConfig = new StringBuilder();
        enumConfig.AppendLine("        // PostgreSQL enum column types");

        foreach (var (schema, table) in tables)
        {
            if (SkipTables.Contains($"{schema}.{table}"))
                continue;

            var key = $"{schema}.{table}";
            columnsByTable.TryGetValue(key, out var columns);
            columns ??= [];
            pkByTable.TryGetValue(key, out var pks);
            pks ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            var className = ToClassName(schema, table);
            var ns = schema switch
            {
                "api" => "CareerPanda.DataAccess.Entities.Api",
                "cp" => "CareerPanda.DataAccess.Entities.Cp",
                "md" => "CareerPanda.DataAccess.Entities.Md",
                _ => "CareerPanda.DataAccess.Entities"
            };

            var folder = schema switch { "api" => "Api", "cp" => "Cp", "md" => "Md", _ => "" };
            var filePath = Path.Combine(outputRoot, folder, $"{className}.cs");

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
            sb.AppendLine($"[Table(\"{table}\", Schema = \"{schema}\")]");
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");

            foreach (var col in columns)
            {
                if (col.DataType == "USER-DEFINED" && !col.UdtName.StartsWith('_'))
                    enumColumns.Add((schema, table, col.Name, col.UdtName));

                var clrType = MapClrType(col);
                var propName = ToPropertyName(col.Name);

                if (pks.Contains(col.Name))
                    sb.AppendLine("    [Key]");

                sb.AppendLine($"    [Column(\"{col.Name}\")]");
                sb.AppendLine($"    public {clrType} {propName} {{ get; set; }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            await File.WriteAllTextAsync(filePath, sb.ToString().TrimEnd() + Environment.NewLine);

            var dbSetName = ToDbSetName(className, table);
            dbSetLines.AppendLine($"    public DbSet<{className}> {dbSetName} {{ get; set; }} = null!;");
        }

        foreach (var grp in enumColumns.GroupBy(e => e.UdtName))
        {
            var schema = grp.First().Schema;
            var udt = grp.First().UdtName;
            foreach (var col in grp)
            {
                var className = ToClassName(col.Schema, col.Table);
                var propName = ToPropertyName(col.Column);
                enumConfig.AppendLine(
                    $"        modelBuilder.Entity<{className}>().Property(e => e.{propName}).HasColumnType(\"{schema}.{udt}\");");
            }
        }

        var dbSetsPath = Path.Combine(dbContextDir, "CareerPandaDbContext.DbSets.cs");
        await File.WriteAllTextAsync(dbSetsPath,
            """
            // <auto-generated />
            using CareerPanda.DataAccess.Entities.Api;
            using CareerPanda.DataAccess.Entities.Cp;
            using CareerPanda.DataAccess.Entities.Md;
            using Microsoft.EntityFrameworkCore;

            namespace CareerPanda.DataAccess.PostgreSQL;

            public partial class CareerPandaDbContext
            {
            """ + dbSetLines + "}\n");

        var enumPath = Path.Combine(dbContextDir, "CareerPandaDbContext.EnumConfig.cs");
        await File.WriteAllTextAsync(enumPath,
            """
            // <auto-generated />
            using CareerPanda.DataAccess.Entities.Api;
            using CareerPanda.DataAccess.Entities.Cp;
            using CareerPanda.DataAccess.Entities.Md;
            using Microsoft.EntityFrameworkCore;

            namespace CareerPanda.DataAccess.PostgreSQL;

            public partial class CareerPandaDbContext
            {
                static partial void ConfigureEnums(ModelBuilder modelBuilder)
                {
            """ + enumConfig + "    }\n}\n");

        Console.WriteLine($"Generated {tables.Count} entities under {outputRoot}");
    }

    private static async Task<List<(string Schema, string Table)>> LoadTablesAsync(NpgsqlConnection conn)
    {
        const string sql = """
            SELECT table_schema, table_name
            FROM information_schema.tables
            WHERE table_schema IN ('api', 'cp', 'md') AND table_type = 'BASE TABLE'
            ORDER BY table_schema, table_name
            """;

        var list = new List<(string, string)>();
        await using var cmd = new NpgsqlCommand(sql, conn);
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            list.Add((reader.GetString(0), reader.GetString(1)));
        return list;
    }

    private static async Task<Dictionary<string, List<ColumnInfo>>> LoadColumnsAsync(NpgsqlConnection conn)
    {
        const string sql = """
            SELECT table_schema, table_name, column_name, data_type, udt_name, is_nullable
            FROM information_schema.columns
            WHERE table_schema IN ('api', 'cp', 'md')
            ORDER BY table_schema, table_name, ordinal_position
            """;

        var dict = new Dictionary<string, List<ColumnInfo>>(StringComparer.OrdinalIgnoreCase);
        await using var cmd = new NpgsqlCommand(sql, conn);
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            var key = $"{reader.GetString(0)}.{reader.GetString(1)}";
            if (!dict.TryGetValue(key, out var list))
            {
                list = [];
                dict[key] = list;
            }

            list.Add(new ColumnInfo(
                reader.GetString(2),
                reader.GetString(3),
                reader.GetString(4),
                reader.GetString(5) == "YES"));
        }

        return dict;
    }

    private static async Task<Dictionary<string, HashSet<string>>> LoadPrimaryKeysAsync(NpgsqlConnection conn)
    {
        const string sql = """
            SELECT tc.table_schema, tc.table_name, kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.constraint_type = 'PRIMARY KEY'
              AND tc.table_schema IN ('api', 'cp', 'md')
            """;

        var dict = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);
        await using var cmd = new NpgsqlCommand(sql, conn);
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            var key = $"{reader.GetString(0)}.{reader.GetString(1)}";
            if (!dict.TryGetValue(key, out var set))
            {
                set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                dict[key] = set;
            }

            set.Add(reader.GetString(2));
        }

        return dict;
    }

    private static string MapClrType(ColumnInfo col)
    {
        var nullable = col.IsNullable ? "?" : "";

        if (col.DataType == "ARRAY")
            return col.IsNullable ? "string[]?" : "string[]";

        if (col.DataType == "USER-DEFINED")
            return "string" + nullable;

        var baseType = col.DataType switch
        {
            "integer" or "smallint" => "int",
            "bigint" => "long",
            "boolean" => "bool",
            "numeric" or "real" or "double precision" => "decimal",
            "timestamp without time zone" or "timestamp with time zone" => "DateTime",
            "date" => "DateOnly",
            "uuid" => "Guid",
            "json" or "jsonb" => "string",
            "character varying" or "text" or "character" => "string",
            _ => "string"
        };

        if (baseType == "string" && col.IsNullable)
            return "string?";

        if (baseType == "string")
            return "string";

        return baseType + nullable;
    }

    private static string ToPropertyName(string column)
    {
        var parts = column.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p =>
            char.ToUpperInvariant(p[0]) + p[1..].ToLowerInvariant()));
    }

    private static string ToClassName(string schema, string table)
    {
        var prefix = schema.ToUpperInvariant() switch
        {
            "API" => "Api",
            "CP" => "Cp",
            "MD" => "Md",
            _ => ""
        };

        var parts = table.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var pascal = string.Concat(parts.Select(CapitalizeWord));

        return prefix + Singularize(pascal);
    }

    private static string Singularize(string name)
    {
        var parts = SplitPascalWords(name);
        if (parts.Count == 0)
            return name;

        parts[^1] = CapitalizeWord(SingularizeWord(parts[^1].ToLowerInvariant()));
        return string.Concat(parts);
    }

    private static string CapitalizeWord(string word)
    {
        if (string.IsNullOrEmpty(word))
            return word;
        return char.ToUpperInvariant(word[0]) + word[1..].ToLowerInvariant();
    }

    private static List<string> SplitPascalWords(string pascal)
    {
        var words = new List<string>();
        var start = 0;
        for (var i = 1; i < pascal.Length; i++)
        {
            if (char.IsUpper(pascal[i]) && char.IsLower(pascal[i - 1]))
            {
                words.Add(pascal[start..i]);
                start = i;
            }
        }
        words.Add(pascal[start..]);
        return words;
    }

    private static string SingularizeWord(string word) => word.ToLowerInvariant() switch
    {
        "users" => "user",
        "jobs" => "job",
        "roles" => "role",
        "companies" => "company",
        "applications" => "application",
        "subscriptions" => "subscription",
        "categories" => "category",
        "countries" => "country",
        "industries" => "industry",
        "skills" => "skill",
        "events" => "event",
        "posts" => "post",
        "comments" => "comment",
        "notifications" => "notification",
        "transactions" => "transaction",
        "referrals" => "referral",
        "certifications" => "certification",
        "educations" => "education",
        "experiences" => "experience",
        "projects" => "project",
        "publications" => "publication",
        "resumes" => "resume",
        "terms" => "term",
        "salaries" => "salary",
        "followers" => "follower",
        "likes" => "like",
        "degrees" => "degree",
        "assignments" => "assignment",
        "profiles" => "profile",
        "requests" => "request",
        "types" => "types",
        "status" => "status",
        "keys" => "key",
        "items" => "item",
        "hosts" => "host",
        "registrations" => "registration",
        "services" => "service",
        "features" => "feature",
        "taxonomies" => "taxonomy",
        "campaigns" => "campaign",
        "submissions" => "submission",
        "runs" => "run",
        "feedbacks" => "feedback",
        "consultations" => "consultation",
        "authorizations" => "authorization",
        "preferences" => "preference",
        "trackings" => "tracking",
        _ when word.EndsWith("ies", StringComparison.OrdinalIgnoreCase) => word[..^3] + "y",
        _ when word.EndsWith("sses", StringComparison.OrdinalIgnoreCase) => word[..^2],
        _ when word.EndsWith("s", StringComparison.OrdinalIgnoreCase) && word.Length > 1 && !word.EndsWith("ss") => word[..^1],
        _ => word
    };

    private static string ToDbSetName(string className, string table)
    {
        var parts = table.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(CapitalizeWord));
    }

    private sealed record ColumnInfo(string Name, string DataType, string UdtName, bool IsNullable);
}
